name: northwind
description: Data collection service
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  binary_data:
    git: "https://github.com/Grabli66/BinaryData"
  device_protocols:
    git: "https://github.com/Grabli66/DeviceProtocols"
  mongo_dart: ^0.3.6

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
